### ISSUE TITLE
Androwarn tool

### ISSUE THREAD

**Issue by xstr8edgepersianx** [AppVet/appvet#5]
Has anyone been able to get the Androwarn tool to work? No matter what I do, I keep getting strange Python errors when I run the tool from the command line.

**Comment by aglynn** [comment]
Yes, I believe several teams got the Androwarn tool working. Have you read through http://appvet.github.io/android-androwarn-toolservice/? If you have tried all that, can you please paste your errors and give more details of how you installed it, the type of server you are using, and other details?

**Comment by xstr8edgepersianx** [comment]
Hello sorry for the delay in response

Yes I followed those instructions exactly. This is the error I receive when I try to manually run androwarn.py on the command line. We are using Red Hat Enterprise Linux 7. 

I get the following error:

I ran the following commands to test the APK for AirBNB:


 python androwarn.py -i SampleApplication/bin/"Airbnb 5.19.0.apk" -v 3 -r html -n


I received the following errors:

Traceback (most recent call last):
  File "androwarn.py", line 116, in <module>
    main(options, arguments)
  File "androwarn.py", line 99, in main
    data = perform_analysis(APK_FILE, a, d, x, no_connection)
  File "/home/dost/androwarn/androwarn/analysis/analysis.py", line 115, in perform_analysis
    ( 'device_settings_harvesting',                      gather_device_settings_harvesting(x) ),
  File "/home/dost/androwarn/androwarn/search/malicious_behaviours/device_settings.py", line 96, in gather_device_settings_harvesting
    result.extend( detect_get_package_info(x) )
  File "/home/dost/androwarn/androwarn/search/malicious_behaviours/device_settings.py", line 79, in detect_get_package_info
    flags = recover_bitwise_flag_settings(flag, PackageManager_PackageInfo)
  File "/home/dost/androwarn/androwarn/util/util.py", line 257, in recover_bitwise_flag_settings
    if (int(flag) & option_value) == option_value :
ValueError: invalid literal for int() with base 10: 'Lcom/google/android/gms/common/GooglePlayServicesUtil;->zzad(Landroid/content/Context;)V'

I receive this error for any APK that i download from the internet.  Something seems to be passing a string that cannot be converted to an integer to that function. I double checked with some Python gurus and they told me the same thing.. we are all at a loss as to what it could be. Any help is greatly appreciated! 

Also another issue that I ran into: No matter which tool I install using the instructions, Androwarn, nor the Sig Verifier, after I am done installing it and I start up Tomcat, when I try to log into Appvet I get an error that says Authentication System Error. It will not let me login at all.  I am attaching a screenshot of that error to this post.
![appvet error 1](https://cloud.githubusercontent.com/assets/19594656/15749489/98fb1cfc-28b0-11e6-9f93-4e5d6c9e409d.JPG)

**Comment by xstr8edgepersianx** [comment]
Hello Thank you for the reply

We are using the Admin username and password is np$@ppvet. These are defined in the AppVetProperties.xml file.  When we restart the tomcat service, we run into this Authentication System Error. Even when we tried creating a new Admin user as well as a new tool provider user, we run into the same error. We also tried restarting the server itself and still the same error. Here is the log entries for our attempt at logging in as the Admin account:


2016-06-03 10:35:30.561-0400 gov.nist.appvet.gwt.server.GWTServiceImpl:authenticateNonSSO line 203
[DEBUG] Adding user-defined default admin 'Admin'
2016-06-03 10:35:30.613-0400 gov.nist.appvet.gwt.server.GWTServiceImpl:authenticateNonSSO line 210
[DEBUG] Added new admin user 'Admin'
2016-06-03 10:35:30.613-0400 gov.nist.appvet.gwt.server.GWTServiceImpl:authenticateNonSSO line 221
[DEBUG] User 'Admin' exists in database.
2016-06-03 10:35:30.636-0400 gov.nist.appvet.gwt.server.GWTServiceImpl:authenticateNonSSO line 223
[DEBUG] User 'Admin' authenticated
2016-06-03 10:35:30.675-0400 gov.nist.appvet.gwt.server.GWTServiceImpl:authenticateNonSSO line 229
[DEBUG] Updated client IP '10.145.131.151' for user 'Admin' updated.
2016-06-03 10:35:30.700-0400 gov.nist.appvet.gwt.server.GWTServiceImpl:authenticateNonSSO line 237
[DEBUG] Updated logon time for user 'Admin'.
2016-06-03 10:35:30.700-0400 gov.nist.appvet.gwt.server.GWTServiceImpl:authenticateNonSSO line 243
[DEBUG] Admin logged into GWT from: 10.145.131.151
2016-06-03 10:35:30.700-0400 gov.nist.appvet.shared.backend.Database:clearExpiredSessions line 110
[DEBUG] Clearing sessions with SQL: DELETE FROM sessions WHERE expiretime < '2016-06-03 10:35:30.7'

If you notice, it says that User Admin is authenticated.  Yet we still get the error.

**Comment by AppVet** [comment]
Can you send me the Tomcat logs in $CATALINA_HOME/logs that have today's date? The issue will likely be found in one of these logs.

**Comment by xstr8edgepersianx** [comment]
[catalina.2016-06.03.txt](https://github.com/AppVet/appvet/files/297920/catalina.2016-06.03.txt)
[catalina.out.txt](https://github.com/AppVet/appvet/files/297923/catalina.out.txt)
[localhost_access_log.2016-06-03.txt](https://github.com/AppVet/appvet/files/297924/localhost_access_log.2016-06-03.txt)

**Comment by xstr8edgepersianx** [comment]
Sorry accidently closed the topic

Here is the manager log

[Uploading manager.2016-06-03.log.txt…]()

**Comment by AppVet** [comment]
Ok, I see a weird exception at the end of catalina.2016-06.03.txt:

java.lang.IllegalArgumentException: Invalid character (CR or LF) found in method name
	at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:228)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1013)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)


I haven't seen this problem before, but it looks like a Tomcat config issue. Are you using SSL? Can you send your $CATALINA_HOME/conf/server.xml file? Please substitute any usernames, passwords, or addresses in your server.xml file with "myusername", "mypassword", and "myaddress" before sending it to me. 

Also, can you send the following just in case:

-Your $APPVET_FILES_HOME/conf/AppVetProperties.xml file? Please substitute any private info before sending to me.
-Version of AppVet?
-Java JRE or JDK version?
-Tomcat version?
-JDBC version?
-Database and version?
-OS and version?

Thanks
-

**Comment by AppVet** [comment]
Also, just FYI that none of our AppVet implementations are using NIO. In other words, we are NOT using the following in server.xml:

  

Instead, we are defining the SSL Connector as:

<Connector SSLEnabled="true" clientAuth="false" keystoreFile="mykeystore.jks" keystorePass="mykeystorepass" maxThreads="xxx" port="xxx" protocol="HTTP/1.1" scheme="https" secure="true" sslEnabledProtocols="xxx,yyy,zzz"/>

For non-SSL, we are using:

    <Connector port="xxxx" protocol="AJP/1.3" redirectPort="yyyy"/>

**Comment by xstr8edgepersianx** [comment]
thank you for your response. Here are the files you requested
[server.xml.txt](https://github.com/AppVet/appvet/files/298227/server.xml.txt)
[AppVetProperties.xml.txt](https://github.com/AppVet/appvet/files/298228/AppVetProperties.xml.txt)

As for the info you requested: 
AppVet Version: 2.2.2
Java JDK Version: 1.8.0_92-bl4
Tomcat version: 8.0.35
I was not able to determine the JDBC version.
MySQL 5.7.12
Red Hat Enterprise Linux 7.2

Thank you

**Comment by xstr8edgepersianx** [comment]
no we are not using SSL for this server . We might in the near future though.

**Comment by AppVet** [comment]
A Google search on the error "java.lang.IllegalArgumentException: Invalid character (CR or LF) found in method name" seems to indicate a number of possible issues. Have you made sure that you are using http in your URLs? What browser and version are you using? I will continue looking into this...

**Comment by xstr8edgepersianx** [comment]
Hello thank you for your help

I am using Chrome version 50.0.2661.102 

Yes when I tried to browse to the site using HTTPS, it did not even load, It loads fine with HTTP

**Comment by AppVet** [comment]
It also appears that prior to the invalid character error, there is an issue with Tomcat's handling of the JDBC driver:
`03-Jun-2016 10:58:47.493 WARNING [http-nio-8080-exec-4] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [appvet] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.`
Not sure if this is the problem, but a fix for this is listed here:
[http://stackoverflow.com/questions/24850091/the-web-application-registered-the-jdbc-driver-com-mysql-jdbc-driver-but-fa](url)
Here, they are recommending moving the JDBC jar file from $CATALINA_HOME/webapps/appvet/WEB-INF/lib/mysql-connector-java-5.1.17-bin.jar to $CATALINA_HOME/lib. If this doesn't work, feel free to email me directly at: appvet.github@gmail.com

**Comment by xstr8edgepersianx** [comment]
Thank you, I will try this today. Sorry for the delay in response. It was the weekend :)
